=== Lil-Carpi/LDM-ASIR/XML/A04/act404_SAD.dtd
<!ELEMENT llibreCuina (recepta+)>
<!-- indica la arrel i que conte dintre -->
<!ELEMENT recepta (ingredients, pasos, tipusCuina, restaurants)>
<!--in dica el ID de la recepte-->
<!ATTLIST recepta id ID #REQUIRED>
<!-- indica el titol de la recepta-->
<!ATTLIST recepta titol CDATA #REQUIRED>
<!-- indica els ingradients y que poden ser mes de un-->
<!ELEMENT ingredients (ingredient+)>
<!--indica el nom de l'ingredient i la quantitat-->
<!ELEMENT ingredient (#PCDATA | quantitat)*>
<!-- indica la referencia del ingredient amb el id i es obligatori-->
<!ATTLIST ingredient ref ID #REQUIRED>
<!-- indica la quantitat de cada ingredient -->
<!ELEMENT quantitat (#PCDATA)>
<!-- comença la estructura dels pasos a seguir i que ni poden haber mes de un-->
<!ELEMENT pasos (pas+)>
<!-- indica el pas-->
<!ELEMENT pas (#PCDATA)>
<!-- indica el tipus de cuina -->
<!ELEMENT tipusCuina (#PCDATA)>
<!-- comença la estructura dels restaurants i que ni poden haber mes de un-->
<!ELEMENT restaurants (restaurant+)>
<!-- indica la informacio del restaurant-->
<!ELEMENT restaurant (nom, carrer?, nombre?, ciutat)>
<!-- indica el id del restaurant-->
<!ATTLIST restaurant idRest ID #IMPLIED>
<!--indica el nom del restaurant-->
<!ELEMENT nom (#PCDATA)>
<!-- indica el carrer del restaurant-->
<!ELEMENT carrer (#PCDATA)>
<!-- indica el numero del restaurant en el carrer -->
<!ELEMENT nombre (#PCDATA)>
<!-- inmdica la ciutat a on esta el restaurant-->
<!ELEMENT ciutat (#PCDATA)>

=== Lil-Carpi/LDM-ASIR/XML/A04/act404_SAD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llibreCuina SYSTEM "act404_SAD.dtd">


<llibreCuina>
    <recepta id="R001" titol="Albergineres farcides">
       <ingredients>
           <ingredient ref="I001">
               carn picada <quantitat>500g</quantitat>
           </ingredient>
           <ingredient ref="I002">
               albarginia <quantitat>4 unitats</quantitat>
           </ingredient>
       </ingredients>
       <pasos>
           <pas>Cuinar la carn</pas>
           <pas>Cuinar alberginies</pas>
       </pasos>
    <tipusCuina>Mediterrània</tipusCuina>
       <restaurants>
           <restaurant idRest="RES01">
               <nom>Can Cuina</nom>
               <carrer>Carrer Major</carrer>
               <nombre>10</nombre>
               <ciutat>Barcelona</ciutat>
           </restaurant>
       </restaurants>
   </recepta>
    <recepta id="R002" titol="Patates fregides">
       <ingredients>
           <ingredient ref="I003">
               patates <quantitat>1kg</quantitat>
           </ingredient>
           <ingredient ref="I004">
               oli <quantitat>al gust</quantitat>
           </ingredient>
       </ingredients>
       <pasos>
           <pas>Pelar i tallar patates</pas>
           <pas>Fregir patates</pas>
       </pasos>
    <tipusCuina>Ràpida</tipusCuina>
       <restaurants>
           <restaurant>
               <nom>El Racó de la Patata</nom>
               <ciutat>Girona</ciutat>
           </restaurant>
       </restaurants>
   </recepta>
</llibreCuina>
